### PR TITLE
Added support for es6module option

### PR DESCRIPTION
**Pull request by DomBlack**
See facebook/react#3401

### CODE REVIEW

**Comment by ddispaltro** [comment]
You want to add a simple test and then I can merge?

**Comment by DomBlack** [comment]
I've added it to both the passing and failing scripted test sets.

**Comment by DomBlack** [comment]
I can't see why that build failed, the key works - I'm assuming travis picked up an old build - can you get it to re-run the test?

**Comment by ddispaltro** [comment]
Can you add it as a separate test? I'll check out Travis.

**Comment by DomBlack** [comment]
As in a separate file inside the existing test projects or a separate set of test projects?

Seems a bit extreme given that all it does is allow the `export` and `import` syntax through (note it doesn't rewrite them)

**Comment by ddispaltro** [comment]
Gotcha good point. Seems fine then.

Maybe the Travis broke because of caching. Try changing the version by
adding snapshot or 5.0.1 and it might work.

Did you test locally?

**Comment by DomBlack** [comment]
I had tested locally without issue, I've moved it to a 0.5.1-SNAPSHOT to see if that fixes Travis.

**Comment by DomBlack** [comment]
@ddispaltro Are you happy to merge this?

**Comment by ddispaltro** [comment]
merged and published, v0.5.1

**Pull request merged**
